#!/bin/sh

# Prolog script that updates the task start times and therefore
# (by trigger) the job start times

PGHOST=queue1 #Put your database server here
PGUSER=sge #Put your database user here (sge probably)
PGDB=sgedb #Put your database name here (sgedb probably)

SGE_ID=${JOB_ID}
if [ "${SGE_TASK_ID}" = "undefined" ]; then
	TASK_NO=1
else
	TASK_NO=${SGE_TASK_ID}
fi

echo "SGE: ${SGE_TASK_ID} - TASK_NO: ${TASK_NO}" > /tmp/epilog

# Now compose the psql command to update the endtime of the task
# check for a returncode and add it to the task, increment attempts,
# increment the donetasks in jobs, and then set status to completed
# if the donetasks = (lasttask - firsttask + 1)
STATUS=3
PSQL_CMD="UPDATE tasks SET endtime = current_timestamp, attempts = attempts + 1"
if [ -e /tmp/${JOB_ID}-${SGE_TASK_ID}-return ]; then
	RETURNCODE=`cat /tmp/${JOB_ID}-${SGE_TASK_ID}-return`
	rm -f /tmp/${JOB_ID}-${SGE_TASK_ID}-return
	# Now fill in the status for the job (not the task)
	if [ "${RETURNCODE}" != "0" ]; then
		STATUS=2
	fi
	PSQL_CMD="${PSQL_CMD}, returncode = ${RETURNCODE}"
fi
PSQL_CMD="${PSQL_CMD} WHERE sgeid = ${SGE_ID} AND taskno = ${TASK_NO};"
PSQL_CMD="${PSQL_CMD}UPDATE jobs SET donetasks = donetasks + 1 WHERE sgeid = ${SGE_ID};"
PSQL_CMD="${PSQL_CMD}UPDATE jobs SET endtime = current_timestamp, status = ${STATUS} WHERE donetasks = (lasttask - firsttask + 1) AND sgeid = ${SGE_ID};"

# Run the task command
psql -d ${PGDB} -U ${PGUSER} -h ${PGHOST} -c "${PSQL_CMD}" &> /dev/null

# Now remove empty logs
[ -r "$SGE_STDOUT_PATH" -a -f "$SGE_STDOUT_PATH" ] && [ ! -s "$SGE_STDOUT_PATH" ] && rm -f $SGE_STDOUT_PATH
[ -r "$SGE_STDERR_PATH" -a -f "$SGE_STDERR_PATH" ] && [ ! -s "$SGE_STDERR_PATH" ] && rm -f $SGE_STDERR_PATH
