#!/bin/bash

# Tiny script to add key/value pairs to job_extras table

PGHOST=queue1     # Postgres database server
PGUSER=sge        # Postgres user
PGDB=sgedb        # Postgres database name

# Check usage
if [ -z $1 ] || [ -z $2 ] || [ -z $3 ]; then
	echo "Usage: $0 <sgeid> <key> <value>"
	exit 1
fi

# Now compose the psql command to insert the row
PSQL_CMD="INSERT INTO job_extras (sgeid, key, value) VALUES ($1, '$2', '$3');"

psql -d ${PGDB} -U ${PGUSER} -h ${PGHOST} -c "${PSQL_CMD}" > /dev/null 2>&1
