#!/bin/sh

# Prolog script that updates the task start times and therefore
# (by trigger) the job start times

PGHOST=queue1 #Put your database server here
PGUSER=sge #Put your database user here (sge probably)
PGDB=sgedb #Put your database name here (sgedb probably)

RHOST=`hostname -s`

SGE_ID=${JOB_ID}
if [ "${SGE_TASK_ID}" = "undefined" ]; then
	TASK_NO=1
else
	TASK_NO=${SGE_TASK_ID}
fi

# Add the stdout/stderr paths to the extras table if this is the first task
# (Does SGE always start the first task first????)
EXT_CMD=""
if [ ${TASK_NO} -eq ${SGE_TASK_FIRST} ]; then
	STDOUT_PATH=`echo ${SGE_STDOUT_PATH} | sed -e 's/\.[0-9]*$//g'`
	STDERR_PATH=`echo ${SGE_STDERR_PATH} | sed -e 's/\.[0-9]*$//g'`
	EXT_CMD="INSERT INTO job_extras (sgeid, key, value) VALUES "
	EXT_CMD="${EXT_CMD}(${SGE_ID}, 'stdout', '${STDOUT_PATH}'); "
	EXT_CMD="${EXT_CMD}INSERT INTO job_extras (sgeid, key, value) VALUES "
	EXT_CMD="${EXT_CMD}(${SGE_ID}, 'stderr', '${STDERR_PATH}');"
fi

# Now compose the psql command to insert the row into the
# tasks table and to update the starttime/status of the job
PSQL_CMD="${EXT_CMD} UPDATE tasks SET starttime = current_timestamp"
PSQL_CMD="${PSQL_CMD}, rhost = '${RHOST}' WHERE sgeid = ${SGE_ID} "
# Figure out if it's batch or not and make the appropriate chunk of psql code
if [ ${SGE_TASK_STEPSIZE} -gt 1 ]; then
	PSQL_CMD="${PSQL_CMD}AND taskno >= ${TASK_NO} "
	PSQL_CMD="${PSQL_CMD}AND taskno < (${TASK_NO} + ${SGE_TASK_STEPSIZE});"
else
	PSQL_CMD="${PSQL_CMD}AND taskno = ${TASK_NO};"
fi
PSQL_CMD="${PSQL_CMD}UPDATE jobs SET starttime = current_timestamp, status = 1 "
PSQL_CMD="${PSQL_CMD}WHERE sgeid = ${SGE_ID} AND starttime IS NULL;"

# Run the task command
psql -d ${PGDB} -U ${PGUSER} -h ${PGHOST} -c "${PSQL_CMD}" > /dev/null 2>&1
