#!/bin/sh

# Prolog script that updates the task start times and therefore
# (by trigger) the job start times

PGHOST=queue1
PGUSER=sge
PGDB=sgedb

SGE_ID=${JOB_ID}
TASK_NO=${SGE_TASK_ID}

# Now compose the psql command to insert the row into the
# tasks table and to update the starttime/status of the job
PSQL_CMD="UPDATE tasks SET starttime = current_timestamp WHERE sgeid = ${SGE_ID} AND taskno = ${TASK_NO};"
PSQL_CMD="${PSQL_CMD}UPDATE jobs SET starttime = current_timestamp, status = 1 WHERE sgeid = ${SGE_ID} AND starttime IS NULL;"

# Run the task command
psql -d ${PGDB} -U ${PGUSER} -h ${PGHOST} -c "${PSQL_CMD}"
